---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  structure:
    channel: beta
ratings:
  paths:
  - Gemfile.lock
  - "**.css"
  - "**.coffee"
  - "**.js"
  - "**.jsx"
  - "**.rb"
exclude_paths:
- config/**/*
- db/**/*
- features/**/*
- spec/**/*
- vendor/**/*
