version: "2"     # required to adjust maintainability checks
plugins:
  structure:
    enabled: false
  duplication:
    enabled: false
  rubocop:
    enabled: true
    channel: "rubocop-0-52"
  eslint:
    enabled: false
exclude_patterns:
- vendor/**/*
- db/**/*
- config/environments/*
- public/**/*
- log/**/*
- tmp/**/*
- app/assets/**/*.html
- app/assets/**/*.css
- app/assets/**/*.less
- app/assets/**/*.json
- app/assets/**/fonts/**/*
- app/assets/**/images/**/*
- app/assets/**/img/**/*
- app/assets/**/cssimg/**/*
- app/assets/shared/lib/**/*
- app/assets/shared/lib-legacy/**/*
- app/assets/lib/**/*
- app/assets/javascripts/**/*
- app/assets/type/**/*
- app/assets/node_modules/**/*
- app/assets/**/node_modules/**/*
- app/assets/asset_list/**/*
- app/assets/gulp/**/*
- app/assets/zest_station/**/*.png